### ISSUE TITLE
Tried replicating COMPAS dataset experiments. Unable to do so.

### ISSUE THREAD

**Issue by tarunhike** [gnobitab/CertifiedMonotonicNetwork#2]
With the value of lambda 1e4 given in the code for COMPAS dataset experiments, the neural network is not getting certified as Monotonic. I tried a range of values also till 1e6 and still the neural network is certified as non-monotonic. Can anyone help me out?

**Comment by gnobitab** [comment]
I just updated the repository with a fixed random seed. The code should be able to reproduce a certified monotonic network now.
